# Copyright (c) 2011-2022 Columbia University, System Level Design Group
# SPDX-License-Identifier: Apache-2.0
EXTRA_CFLAGS ?= -I$(DRIVERS)/../../../../accelerators/stratus_hls/fft_stratus/sw/linux/include -I$(DRIVERS)/../../../../accelerators/stratus_hls/conv2d_stratus/sw/linux/include
APPNAME := spikehard
include $(DRIVERS)/common.mk
