#ifndef SPIKEHARD_SW_LIB_SPIKEHARD_ARCHITECTURE_H_INCLUDED
#define SPIKEHARD_SW_LIB_SPIKEHARD_ARCHITECTURE_H_INCLUDED

#define MAX_DIMENSION_X 512
#define MAX_DIMENSION_Y 512
#define GRID_DIMENSION_X 4
#define GRID_DIMENSION_Y 4
#define OUTPUT_CORE_X_COORDINATE 0
#define OUTPUT_CORE_Y_COORDINATE 0
#define NUM_OUTPUTS 16
#define NUM_NEURONS 32
#define NUM_AXONS 32

#endif // SPIKEHARD_SW_LIB_SPIKEHARD_ARCHITECTURE_H_INCLUDED